name: 'WordPress Plugin Deploy by NextGenThemes'
description: 'Deploy to the WordPress Plugin Repository'
author: 'nextgenthemes'
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  svn_user:
    description: Should be added with Github secrets
    required: true
  svn_pass:
    description: Should be added with Github secrets
    required: true
  version:
    description: Git tag you want to deploy, required unless you just update readme and assets
    required: false
  workdir:
    description: Relative path to where the main plugin file is.
    required: false
  build_dirs:
    description: Comma separated list of folders to include in distribution.
    required: false
  readme-and-assets-only:
    description: Only update readme and assets, boolean
    required: false
  verbose:
    description: Verbose output, boolean
    required: false
  generate_zip:
    description: Generate zip file of the plugin
    required: false
    default: 'true'

outputs:
  zip-path:
    description: Path to the generated zip file
    value: ${{ steps.deploy.outputs.zip-path }}

runs:
  using: 'composite'
  steps:
    - name: Setup Deno
      uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4 https://github.com/denoland/setup-deno/releases
      with:
        deno-version: v2.x

    - id: deploy
      run: >
        deno run --allow-all
        ${{ github.action_path }}/src/wp-plugin-deploy.ts
        --workdir='${{ inputs.workdir }}'
        --build-dirs='${{ inputs.build_dirs }}'
        --version='${{ inputs.version }}'
        --svn-user='${{ inputs.svn_user }}'
        --svn-pass='${{ inputs.svn_pass }}'
        ${{ ( inputs.readme-and-assets-only && inputs.readme-and-assets-only != 'false' ) && '--readme-and-assets-only' }}
        ${{ ( inputs.verbose && inputs.verbose != 'false' ) && '--verbose' }}
        ${{ ( inputs.generate_zip && inputs.generate_zip != 'false' ) && '--generate-zip' }}
      shell: bash
