name: 'WordPress Plugin Deploy by NextgenThemes'
description: 'Deploy to the WordPress Plugin Repository'
author: 'nextgenthemes' # inspired by 10up action
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  svn_user:
    required: true
  svn_pass:
    required: true
  version:
    description: Git tag you want to deploy, required unless you just update readme and assets
    required: false
  workdir:
    description: Relative path to where the main plugin file is.
    required: false
  build_dirs:
    description: Comma separated list of folders to include in distribution.
    required: false
  switches:
    description: Use --readme-only and/or --dry-run
    required: false

runs:
  using: 'composite'
  steps:
    - run: php --version
      shell: bash

    - run: pwd
      shell: bash

    - run: cat ${{ github.action_path }}/wp-plugin-deploy.php
      #run: ${{ github.action_path }}/wp-plugin-deploy.php --workdir=${{ inputs.workdir }} --build-dirs=${{ inputs.build_dirs }} --version=${{ inputs.version }} --svn-user=${{ inputs.svn_user }} --svn-pass=${{ inputs.svn_pass }} ${{ inputs.switches }}
      shell: bash
