name: 'WordPress Plugin Deploy by NextgenThemes'
description: 'Deploy to the WordPress Plugin Repository'
author: 'nextgenthemes' # inspired by 10up action
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  svn_user:
    required: true
  svn_pass:
    required: true
  version:
    description: Git tag you want to deploy, required unless you just update readme and assets
    required: false
  workdir:
    description: Relative path to where the main plugin file is.
    required: false
  build_dirs:
    description: Comma separated list of folders to include in distribution.
    required: false
  readme-and-assets-only:
    required: false
  dry-run:
    required: false
  verbose:
    required: false

runs:
  using: 'composite'
  steps:
    - run: php --version
      shell: bash

    - run: pwd
      shell: bash

    # https://github.com/actions/runner/issues/2238
    - run: >
        ${{ github.action_path }}/wp-plugin-deploy.php
        --workdir='${{ inputs.workdir }}'
        --build-dirs='${{ inputs.build_dirs }}'
        --version='${{ inputs.version }}'
        --svn-user='${{ inputs.svn_user }}'
        --svn-pass='${{ inputs.svn_pass }}'
        ${{ ( inputs.readme-and-assets-only == 'true' || inputs.readme-and-assets-only ) && '--readme-and-assets-only' }}
        ${{ ( inputs.dry-run == 'true' || inputs.dry-run ) && '--dry-run' }}
        ${{ ( inputs.verbose == 'true' || inputs.verbose ) && '--verbose' }}
      shell: bash
